### ISSUE TITLE
Running Example

### ISSUE THREAD

**Issue by NoahMarconi** [ricmoo/ethers-airdrop#1]
Trying to run the example and get an unhandled promise rejection. Was there a step to the setup that I missed outside of `npm install`?

```
$ node examples/pi-day-n00b-token.js
5251718
(node:64281) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'transactions' of null
    at /Users/noahmarconi/ethers-airdrop/examples/pi-day-n00b-token.js:25:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:64281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64281) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ricmoo** [comment]
Do you have a mainnet (homestead) node running on http://localhost:8545 and fully synced?

That error means it could not find block 5,251,718, which means the block doesn't exist; which could be the case if your local node is either not yet synced, or a different network (like the Ropsten testnet).

**Comment by NoahMarconi** [comment]
I see what I'm missing. I wasn't running a local geth node. Switching to `InfuraProvider` got me up and running

**Comment by ricmoo** [comment]
Keep in mind, that it makes a LOT of calls, so a local homestead node is highly recommended.

If you are trying to claim one of your tokens, I can send you your merkle proof. If you are just looking to play around with it, I recommend reducing the size from 1000000 token holders.

I should make a smaller example for people to play with. :)

**Comment by NoahMarconi** [comment]
Thanks, I'll do that instead. I'm not claiming tokens, just playing with the example.

**Comment by ricmoo** [comment]
In that case, you may also be interested in this:

https://ropsten.etherscan.io/address/0x688d7ccac5c2fdac9be458ad0d9ab6a6735014b1

It's the same contract and data deployed on ropsten. Processing the file takes a long time, about 3-4 hours. And using the file takes about 20 minutes per deploy/redeem. There is a technique to chunk the merkle tree I would implement if this becomes popular, which splits the merkle tree across many smaller files, which are easier to share and quicker to process. :)

**Comment by NoahMarconi** [comment]
Very cool, any chance I can help with the chunking? I'm looking at a use case that requires repeated use for multiparty token payouts.
